services:
  service:
    build: .
    restart: always
    ports:
      - "5000"
    volumes:
      - ./flag.txt:/flag.txt:ro
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M
    networks:
      - net

networks:
    net:
        name: cnsc_frp_containers
        external: true